/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface definitions {
  CategoryModel: {
    id?: number;
    name?: string;
    pageSizeOptions?: string;
    description?: string;
    parentCategoryId?: number;
    pictureId?: number;
    pageSize?: number;
    showOnHomepage?: boolean;
    includeInTopMenu?: boolean;
    published?: boolean;
    deleted?: boolean;
    displayOrder?: number;
    createdOnUtc?: string;
    updatedOnUtc?: string;
  };
  OperationHistoryModel: {
    objectType?: string;
    objectId?: string;
    objectName?: string;
    changeType?: string;
    fieldName?: string;
    originalValue?: string;
    newValue?: string;
    comments?: string;
    modifiedById?: string;
    modifiedBy?: string;
    modifiedDate?: string;
  };
  PictureBinaryModel: {
    id?: number;
    mimeType?: string;
    seoFilename?: string;
    altAttribute?: string;
    titleAttribute?: string;
    isNew?: boolean;
    virtualPath?: string;
    binaryData?: string;
  };
}
